/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<
      'Home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '404': RouteRecordInfo<
      '404',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'Dashboard': RouteRecordInfo<
      'Dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Messaging Integrations': RouteRecordInfo<
      'Messaging Integrations',
      '/sunco/integrations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Switchboard Configuration': RouteRecordInfo<
      'Switchboard Configuration',
      '/sunco/integrations/switchboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SunCo Notifications': RouteRecordInfo<
      'SunCo Notifications',
      '/sunco/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'API Snippets': RouteRecordInfo<
      'API Snippets',
      '/sunco/snippets/api-body',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Widget Snippets': RouteRecordInfo<
      'Widget Snippets',
      '/sunco/snippets/web-widget',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SunCo templates': RouteRecordInfo<
      'SunCo templates',
      '/sunco/templates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Whatsapp templates': RouteRecordInfo<
      'Whatsapp templates',
      '/sunco/templates/whatsapp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Users': RouteRecordInfo<
      'Users',
      '/sunco/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SunCo User': RouteRecordInfo<
      'SunCo User',
      '/sunco/users/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'Find user by email identity': RouteRecordInfo<
      'Find user by email identity',
      '/sunco/users/list-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Testing area': RouteRecordInfo<
      'Testing area',
      '/testing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Zendesk Tools': RouteRecordInfo<
      'Zendesk Tools',
      '/zendesk',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'Home'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '404'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | 'Dashboard'
      views:
        | never
    }
    'src/pages/sunco/integrations/index.vue': {
      routes:
        | 'Messaging Integrations'
      views:
        | never
    }
    'src/pages/sunco/integrations/switchboard/index.vue': {
      routes:
        | 'Switchboard Configuration'
      views:
        | never
    }
    'src/pages/sunco/notifications/index.vue': {
      routes:
        | 'SunCo Notifications'
      views:
        | never
    }
    'src/pages/sunco/snippets/api-body/index.vue': {
      routes:
        | 'API Snippets'
      views:
        | never
    }
    'src/pages/sunco/snippets/web-widget/index.vue': {
      routes:
        | 'Widget Snippets'
      views:
        | never
    }
    'src/pages/sunco/templates/index.vue': {
      routes:
        | 'SunCo templates'
      views:
        | never
    }
    'src/pages/sunco/templates/whatsapp.vue': {
      routes:
        | 'Whatsapp templates'
      views:
        | never
    }
    'src/pages/sunco/users/index.vue': {
      routes:
        | 'Users'
      views:
        | never
    }
    'src/pages/sunco/users/[id].vue': {
      routes:
        | 'SunCo User'
      views:
        | never
    }
    'src/pages/sunco/users/list-users/index.vue': {
      routes:
        | 'Find user by email identity'
      views:
        | never
    }
    'src/pages/testing.vue': {
      routes:
        | 'Testing area'
      views:
        | never
    }
    'src/pages/zendesk/index.vue': {
      routes:
        | 'Zendesk Tools'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
