/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<'Home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    'Dashboard': RouteRecordInfo<'Dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'Messaging Integrations': RouteRecordInfo<'Messaging Integrations', '/sunco/integrations', Record<never, never>, Record<never, never>>,
    'Switchboard Configuration': RouteRecordInfo<'Switchboard Configuration', '/sunco/integrations/switchboard', Record<never, never>, Record<never, never>>,
    'SunCo Notifications': RouteRecordInfo<'SunCo Notifications', '/sunco/notifications', Record<never, never>, Record<never, never>>,
    'API Snippets': RouteRecordInfo<'API Snippets', '/sunco/snippets/api-body', Record<never, never>, Record<never, never>>,
    'Widget Snippets': RouteRecordInfo<'Widget Snippets', '/sunco/snippets/web-widget', Record<never, never>, Record<never, never>>,
    'SunCo templates': RouteRecordInfo<'SunCo templates', '/sunco/templates', Record<never, never>, Record<never, never>>,
    'Whatsapp templates': RouteRecordInfo<'Whatsapp templates', '/sunco/templates/whatsapp', Record<never, never>, Record<never, never>>,
    'Users': RouteRecordInfo<'Users', '/sunco/users', Record<never, never>, Record<never, never>>,
    'SunCo User': RouteRecordInfo<'SunCo User', '/sunco/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'Testing area': RouteRecordInfo<'Testing area', '/testing', Record<never, never>, Record<never, never>>,
    'Zendesk Tools': RouteRecordInfo<'Zendesk Tools', '/zendesk', Record<never, never>, Record<never, never>>,
  }
}
